import db from '../database/db.js';
import { authMiddleware } from '../middleware/auth.js';
import { exec } from 'child_process';
import { promisify } from 'util';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';

const execAsync = promisify(exec);
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// WhatsApp session storage
const WA_SESSION_DIR = process.env.WA_SESSION_DIR || '/data/whatsapp';

// Ensure session directory exists
if (!fs.existsSync(WA_SESSION_DIR)) {
  fs.mkdirSync(WA_SESSION_DIR, { recursive: true });
}

export function setupWhatsAppRoutes(app) {
  // Get WhatsApp status
  app.get('/api/admin/whatsapp', authMiddleware, (req, res) => {
    const session = db.prepare('SELECT * FROM whatsapp_sessions ORDER BY created_at DESC LIMIT 1').get();
    const enabled = db.prepare("SELECT value FROM settings WHERE key = 'whatsapp_enabled'").get();
    res.json({
      enabled: enabled?.value === '1',
      session: session || null
    });
  });

  // Generate QR code
  app.post('/api/admin/whatsapp/qr', authMiddleware, async (req, res) => {
    try {
      const sessionId = `sf_${Date.now()}`;
      
      // Create a simple QR generation using a Node.js script
      const qrScript = path.join(__dirname, '..', 'services', 'whatsapp_qr.js');
      
      // For now, return a placeholder - the actual QR will be generated by the WhatsApp service
      // Store session in DB
      db.prepare('INSERT OR REPLACE INTO whatsapp_sessions (session_id, status) VALUES (?, ?)').run(sessionId, 'waiting_qr');
      
      // Start WhatsApp Web session using whatsapp-web.js
      const waServicePath = path.join(__dirname, '..', 'services', 'whatsapp_service.js');
      
      // Check if service file exists
      if (fs.existsSync(waServicePath)) {
        // Start in background
        const child = exec(`node ${waServicePath} ${sessionId}`, {
          cwd: path.join(__dirname, '..', '..'),
          detached: true,
          stdio: 'ignore'
        });
        child.unref();
      }

      res.json({ 
        success: true, 
        sessionId,
        message: 'Generando QR... Escanea en unos segundos.',
        qr_placeholder: true
      });
    } catch (err) {
      console.error('WhatsApp QR error:', err);
      res.status(500).json({ error: 'Error generando QR' });
    }
  });

  // Get QR code image
  app.get('/api/admin/whatsapp/qr-image', authMiddleware, (req, res) => {
    const session = db.prepare('SELECT qr_code, status FROM whatsapp_sessions ORDER BY created_at DESC LIMIT 1').get();
    if (!session || !session.qr_code) {
      return res.status(404).json({ error: 'QR no disponible. Genera uno primero.' });
    }
    // If it's a data URL, return it directly
    if (session.qr_code.startsWith('data:image')) {
      return res.json({ qr_code: session.qr_code, status: session.status, is_data_url: true });
    }
    // Otherwise return the raw QR string
    res.json({ qr_code: session.qr_code, status: session.status });
  });

  // Check connection status
  app.get('/api/admin/whatsapp/status', authMiddleware, (req, res) => {
    const session = db.prepare('SELECT * FROM whatsapp_sessions ORDER BY created_at DESC LIMIT 1').get();
    if (!session) {
      return res.json({ status: 'disconnected', phone: '' });
    }
    res.json({ 
      status: session.status, 
      phone: session.phone,
      connected_at: session.connected_at,
      last_seen: session.last_seen
    });
  });

  // Disconnect WhatsApp
  app.post('/api/admin/whatsapp/disconnect', authMiddleware, (req, res) => {
    db.prepare('UPDATE whatsapp_sessions SET status = ?, qr_code = ? WHERE status = ?').run('disconnected', '', 'connected');
    db.prepare("UPDATE settings SET value = ? WHERE key = 'whatsapp_enabled'").run('0');
    res.json({ success: true });
  });

  // Toggle WhatsApp enabled
  app.post('/api/admin/whatsapp/toggle', authMiddleware, (req, res) => {
    const { enabled } = req.body;
    db.prepare("UPDATE settings SET value = ? WHERE key = 'whatsapp_enabled'").run(enabled ? '1' : '0');
    res.json({ success: true, enabled: enabled ? '1' : '0' });
  });

  // Get WhatsApp messages
  app.get('/api/admin/whatsapp/messages', authMiddleware, (req, res) => {
    const { limit = 50, offset = 0 } = req.query;
    const messages = db.prepare(`
      SELECT * FROM whatsapp_messages 
      ORDER BY created_at DESC 
      LIMIT ? OFFSET ?
    `).all(parseInt(limit), parseInt(offset));
    const total = db.prepare('SELECT COUNT(*) as count FROM whatsapp_messages').get().count;
    res.json({ messages, total });
  });

  // Send WhatsApp message
  app.post('/api/admin/whatsapp/send', authMiddleware, (req, res) => {
    const { to, message } = req.body;
    if (!to || !message) {
      return res.status(400).json({ error: 'Destinatario y mensaje requeridos' });
    }

    const session = db.prepare("SELECT value FROM settings WHERE key = 'whatsapp_enabled'").get();
    if (session?.value !== '1') {
      return res.status(400).json({ error: 'WhatsApp no está conectado' });
    }

    // Store message as pending
    const result = db.prepare(
      'INSERT INTO whatsapp_messages (session_id, direction, to_number, message, status) VALUES (?, ?, ?, ?, ?)'
    ).run('manual', 'outgoing', to, message, 'pending');

    res.json({ success: true, message_id: result.lastInsertRowid });
  });
}
